language: python
python:
  - 3.6
  - 2.7
env:
  - SKLEARN_VERSION="0.22.1"
  - SKLEARN_VERSION="0.21.3"
  - SKLEARN_VERSION="0.20.4"
  - SKLEARN_VERSION="0.19.2"
jobs:
  exclude:
    - python: 2.7
      env: SKLEARN_VERSION="0.21.3"
    - python: 2.7
      env: SKLEARN_VERSION="0.22.1"
os: linux
dist: bionic
cache: pip
addons:
  apt:
    update: true
    packages:
      - openjdk-8-jdk
install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
  - pip install -e .
script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  - pip install scikit-learn==$SKLEARN_VERSION
  - bash python/run-tests.sh
