name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"] # 3.11 not working with Spark yet
        sklearn-version: ["0.22.2", "1.2.2"]
        exclude:
          - python-version: "3.9"
            sklearn-version: "0.22.2"
          - python-version: "3.10"
            sklearn-version: "0.22.2"
          - python-version: "3.11"
            sklearn-version: "0.22.2"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements-tests.txt
          pip install -e .

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: adopt

      - name: Install scikit-learn
        run: pip install scikit-learn==${{ matrix.sklearn-version }}

      - name: Install pyspark
        run: pip install pyspark==3.3.2

      - name: Run tests (pytest)
        run: pytest --disable-warnings -vv -rxXs python/test

      # - name: Run tests (nose)
      #   run: bash python/run-tests.sh
